### ISSUE TITLE
iOS11下icon没有的问题只要去build phase里面把Copy Bundle Resources拖到最后一步就可以了，没必要改podfile的

### ISSUE THREAD

**Issue by casatwy** [mythkiven/developTips#1]
![wechatimg1050](https://user-images.githubusercontent.com/1005781/30681066-0642f40a-9ed6-11e7-9778-c4d312d10e4d.jpeg)

**Comment by gdfyj90** [comment]
你这个方法在xcode9正式版无效。。

**Comment by mythkiven** [comment]
感谢 @casatwy 和 @gdfyj90 的补充反馈，这里统一说明一下 👇

**关于 @casatwy 的建议**

「把 Copy Bundle Resources 拖到最后一步」确实是更简洁的方案，大多数情况下**不需要改 Podfile**。当时写 [ios11AppIcon.md](./devTips/ios11AppIcon.md) 是因为部分 CocoaPods 版本（1.2.x + Xcode 9 GM）下，actool 编译 Asset Catalog 时缺少 `--app-icon` 参数导致图标丢失，修改 `Pods-xxx-resources.sh` 是从根源修复脚本。

**推荐优先级：**

1. ✅ **首选**：Build Phases → 将 `Copy Bundle Resources` 移到最末尾（@casatwy 的方案）
2. ✅ **次选**：升级 CocoaPods 到较新版本（1.3+ 已修复该问题）
3. ⚠️ **兜底**：仅在上述方案无效时，才考虑修改 Podfile post_install 脚本

**关于 @gdfyj90 提到的 Xcode 9 正式版无效**

Xcode 9 正式版 vs GM 之间 CocoaPods 脚本行为有差异，如果 Copy Bundle Resources 调整后仍无效，可以尝试：
- `pod deintegrate && pod install` 重新生成 Pods 脚本
- 确认 `ASSETCATALOG_COMPILER_APPICON_NAME` 在 Build Settings 中已正确设置
- 清理 DerivedData 后全量编译

该 issue 涉及的 iOS 11 + Xcode 9 环境已较久远，上述 devTip 文档后续会补充更简洁的方案说明。感谢两位 🙏
